### ISSUE TITLE
Another victim of issue #53?

### ISSUE THREAD

**Issue by RandomInsano** [avr-llvm/llvm#55] opened 2015-03-08 06:08 UTC
This is the test I've fiddled with:

```
; RUN: llvm-mc -triple avr-none -show-encoding < %s | FileCheck %s

foo:

  sbr r16, 0x00
  sbr r31, 0xff
  
; CHECK: sbr r16, 0x00                 ; encoding: [0x00,0x60]
; CHECK: sbr r31, 0xff                 ; encoding: [0xff,0x6f]
```

I’ve confirmed this via AVR-GCC:

```
sbr r16, 0x00
sbr r31, 0xff
04000000 0060 FF6F 2E
```

But I’m hitting this during the test:

```
<stdin>:6:12: error: invalid operand for instruction
  sbr r16, 0x00
```

Does this have anything to do with issue #53?

**Comment by dylanmckay** [comment] 2015-03-08 06:13
There are no labels in this example, therefore it is not related to the local labels issue.

I will do some debugging to figure out the cause of this issue,

**Comment by dylanmckay** [comment] 2015-03-08 07:24
I believe this is a duplicate of #53 and is now fixed.

**Closed by dylanmckay** 2015-03-08 07:24 UTC
